packages:
  - packages/*
  - examples/*
catalog:
  '@eslint/js': ^9.17.0
  '@types/react': ^18.3.18
  '@types/react-dom': ^18.3.5
  '@vitejs/plugin-react': ^4.3.4
  eslint: ^9.17.0
  eslint-plugin-react-hooks: ^5.0.0
  eslint-plugin-react-refresh: ^0.4.16
  globals: ^15.14.0
  react: ^18.3.1
  react-dom: ^18.3.1
  typescript: ~5.6.2
  typescript-eslint: ^8.18.2
  vite: ^6.0.5
  tailwindcss: ^4.0.0
  '@tailwindcss/vite': ^4.0.0
  immer: ^10.1.1
